<a href="https://colab.research.google.com/github/ramonparaiba/data-science-studies/blob/main/DataSUS_LEARN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importação das bases de dados
Inicialmente, busquei no Site SINAN pelos dados de acidentes por animais peçonhentos.

https://portalsinan.saude.gov.br/o-sinan

Este mesmo fluxo poderá ser adotando para análises futuras

# Transformar a Base em CSV

No site https://datasus.saude.gov.br/transferencia-de-arquivos/

Deve-se buscar pelo app windows TABWIN/TABNET, a partir dele é possível transformar o arquivo .DBC em .DBF e depois em .CSV

# Importação de Bibliotecas

In [1]:
#Pandas

import pandas as pd

In [2]:
#Visualizar todas as tabelas
pd.options.display.max_columns = None

In [4]:
#Ler csv
dados = pd.read_csv("/content/ANIMBR17.csv", encoding='latin1')
dados

<ipython-input-4-963f0b00406f>:2: DtypeWarning: Columns (10,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  dados = pd.read_csv("/content/ANIMBR17.csv", encoding='latin1')

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,1.0,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,2,X29,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,2,X29,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,2,X29,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,2,X29,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,2,X29,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,2,X29,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,2,X29,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

#Ajustando a tabela
* As tabelas, geralmente, são geradas a partir de formulários e instrumentos próprios.
* Devemos, ajustar a tabela para ela se tornar legível
* neste caso, recorremos ao site https://portalsinan.saude.gov.br/acidente-por-animais-peconhentos
*O qual apresenta o dicionário de dados para decifrarmos a tabela.

In [5]:
#Listar as colunas
dados.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

Escolher quais colunas manter, copianda a lista gerada na célula anterior, e apagand o nome das que não nos serão úteis.

In [6]:
#Neste caso apenas removi 'TP_NOT', 'ID_AGRAVO'. este passo pode variar entre cada caso

colunas_manter = ['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA']

In [7]:
#Substituir o dataframe atual, pelo novo apenas com as colunas que queremos manter
dados = dados[colunas_manter].reset_index(drop=True)
dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,1.0,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

Substituir os nomes das colunas utilizando o método **Replace**

Ao avaliar o dicionário de dados, percebe-se que muitas variáveis apresentam apenas SIM e o NÃO. para essas criaremos um mini dicionário.

In [8]:
dados['MCLI_LOCAL'] = dados['MCLI_LOCAL'].replace({
    1:'Sim',
    2:'Não',
    9:'Ignorado'
})

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,Sim,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,Sim,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

Buscar agora todas as séries/colunas que possuem a codificação SIM/NÃO, e vamos aplicar um laço FOR.

In [9]:
colunas_sim_nao = ['MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS', 'CLI_LOCAL_',
                   'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL',
                   'CLI_OUTR_2', 'CON_SOROTE', 'COM_LOC', 'COM_SECUND', 'COM_NECROS', 'COM_COMPOR',
                   'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC',
                   'COM_CHOQUE', 'DOENCA_TRA']

for serie in colunas_sim_nao:
  dados[serie] = dados[serie].replace({1:'Sim', 2:'Não',9:'Ignorado'})

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,,,20191018

Ajustar os formatos de Data

In [11]:
colunas_data = ['DT_NOTIFIC','DT_SIN_PRI', 'DT_INVEST', 'ANT_DT_ACI', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA' ]

for serie in colunas_data:
  dados[serie] = pd.to_datetime(dados[serie], format='%Y%m%d', errors='coerce')

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,NaT,2017-02-02,2017-02-09
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaT,2017-01-02,2017-01-16
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-01,2017-01-25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-02-13,2017-02-17
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-02,2017-03-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2018-02-10,2018-08-10
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18

In [10]:
dados.columns

Index(['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP',
       'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N',
       'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI',
       'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'ANT_DT_ACI',
       'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_', 'ANT_LOCA_1',
       'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS',
       'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR',
       'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2', 'CLI_OUTR_3',
       'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN', 'ANI_ARANHA',
       'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS', 'NU_AMPOL_1',
       'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7', 'NU_AMPO_5',
       'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND', 'COM_NECROS',
       'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL',
       'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA', 'EVOLUCAO',
       'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

### Reescrita das codificações do dicionário de dados.
Nesta etapa, deve-se reescrever TODAS as codificações do dicionário de dados. Para isso, usamos novamente a função REPLACE

In [ ]:
dados['ANT_ZONA'] = dados['ANT_ZONA'].replace({
    1 : 'Urbana',
    2 : 'Rural',
    3 : 'Periurbana',
    9 : 'Ignorado',
})