<a href="https://colab.research.google.com/github/ramonparaiba/data-science-studies/blob/main/DataSUS_LEARN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importação das bases de dados
Inicialmente, busquei no Site SINAN pelos dados de acidentes por animais peçonhentos.

https://portalsinan.saude.gov.br/o-sinan

Este mesmo fluxo poderá ser adotando para análises futuras

# Transformar a Base em CSV

No site https://datasus.saude.gov.br/transferencia-de-arquivos/

Deve-se buscar pelo app windows TABWIN/TABNET, a partir dele é possível transformar o arquivo .DBC em .DBF e depois em .CSV

# Importação de Bibliotecas

In [1]:
#Pandas

import pandas as pd

In [2]:
#Visualizar todas as tabelas
pd.options.display.max_columns = None

In [4]:
#Ler csv
dados = pd.read_csv("/content/ANIMBR17.csv", encoding='latin1')
dados

<ipython-input-4-963f0b00406f>:2: DtypeWarning: Columns (10,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  dados = pd.read_csv("/content/ANIMBR17.csv", encoding='latin1')

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,1.0,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,2,X29,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,2,X29,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,2,X29,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,2,X29,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,2,X29,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,2,X29,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,2,X29,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,2,X29,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

#Ajustando a tabela
* As tabelas, geralmente, são geradas a partir de formulários e instrumentos próprios.
* Devemos, ajustar a tabela para ela se tornar legível
* neste caso, recorremos ao site https://portalsinan.saude.gov.br/acidente-por-animais-peconhentos
*O qual apresenta o dicionário de dados para decifrarmos a tabela.

In [5]:
#Listar as colunas
dados.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

Escolher quais colunas manter, copianda a lista gerada na célula anterior, e apagand o nome das que não nos serão úteis.

In [6]:
#Neste caso apenas removi 'TP_NOT', 'ID_AGRAVO'. este passo pode variar entre cada caso

colunas_manter = ['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_',
       'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO',
       'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO',
       'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2',
       'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN',
       'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS',
       'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7',
       'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND',
       'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM',
       'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA',
       'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA']

In [7]:
#Substituir o dataframe atual, pelo novo apenas com as colunas que queremos manter
dados = dados[colunas_manter].reset_index(drop=True)
dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,1.0,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

Substituir os nomes das colunas utilizando o método **Replace**

Ao avaliar o dicionário de dados, percebe-se que muitas variáveis apresentam apenas SIM e o NÃO. para essas criaremos um mini dicionário.

In [8]:
dados['MCLI_LOCAL'] = dados['MCLI_LOCAL'].replace({
    1:'Sim',
    2:'Não',
    9:'Ignorado'
})

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,Sim,9.0,1.0,9.0,9.0,9.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,9.0,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,9.0,0,0,0,0,0,0,0,0,0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,Sim,1.0,1.0,1.0,1.0,2.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,1.0,8,0,0,0,0,0,0,0,0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,Sim,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,0,0,0,0,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2.0,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,Sim,1.0,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,1.0,0,0,0,8,0,0,0,0,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,,,20191018

Buscar agora todas as séries/colunas que possuem a codificação SIM/NÃO, e vamos aplicar um laço FOR.

In [9]:
colunas_sim_nao = ['MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS', 'CLI_LOCAL_',
                   'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL',
                   'CLI_OUTR_2', 'CON_SOROTE', 'COM_LOC', 'COM_SECUND', 'COM_NECROS', 'COM_COMPOR',
                   'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC',
                   'COM_CHOQUE', 'DOENCA_TRA']

for serie in colunas_sim_nao:
  dados[serie] = dados[serie].replace({1:'Sim', 2:'Não',9:'Ignorado'})

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,20170101,201701,2017,29,291080,1381.0,20170101,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,20170101,NaN,20170101,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,,20170202,20170209
1,20170101,201701,2017,35,352620,1335.0,20170101,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,20170101,NaN,20170101,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,,20170102,20170116
2,20170101,201701,2017,13,130360,5584.0,20160515,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,20170101,612005.0,20160115,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170101,20170125
3,20170101,201701,2017,41,412010,1357.0,20170101,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,20170101,999993.0,20170101,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170213,20170217
4,20170101,201701,2017,26,261160,1497.0,20170101,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,20170101,NaN,20170101,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20170102,20170328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,20171231,201801,2017,22,221050,NaN,20171231,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,20171231,999991.0,20171231,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222854,20171231,201801,2017,22,221050,NaN,20171231,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,20171231,999992.0,20171231,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20171231,20180117
222855,20171231,201801,2017,31,311680,1450.0,20171231,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,20171231,782305.0,20171231,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,,20180129,20180129
222856,20171231,201801,2017,41,410180,1356.0,20171230,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,20171231,NaN,20171230,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,,20180210,20180810
222857,20171231,201801,2017,29,293330,1398.0,20171231,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,20171231,NaN,20171231,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,,,20191018

Ajustar os formatos de Data

In [11]:
colunas_data = ['DT_NOTIFIC','DT_SIN_PRI', 'DT_INVEST', 'ANT_DT_ACI', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA' ]

for serie in colunas_data:
  dados[serie] = pd.to_datetime(dados[serie], format='%Y%m%d', errors='coerce')

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,6.0,2.0,10.0,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,9.0,6.0,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,1.0,NaT,2017-02-02,2017-02-09
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,9.0,9.0,9.0,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,1.0,9.0,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,9.0,NaN,9.0,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaT,2017-01-02,2017-01-16
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,5.0,5.0,0.0,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,5.0,9.0,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,9.0,1.0,NaN,1.0,NaN,NaN,3.0,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-01,2017-01-25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,5.0,1.0,6.0,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-02-13,2017-02-17
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,6.0,9.0,10.0,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,1.0,9.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-01-02,2017-03-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,6.0,4.0,3.0,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,1.0,9.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,5.0,4.0,3.0,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,1.0,4.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,NaN,NaN,NaN,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2017-12-31,2018-01-17
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,6.0,4.0,1.0,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,2.0,10.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,NaN,NaN,1.0,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,5.0,1.0,9.0,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,5.0,1.0,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,2.0,NaN,NaN,2.0,NaN,1.0,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,1.0,NaT,2018-02-10,2018-08-10
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,9.0,1.0,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,10.0,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,NaN,2.0,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18

In [10]:
dados.columns

Index(['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT', 'ID_MUNICIP',
       'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N',
       'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI',
       'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'ANT_DT_ACI',
       'ANT_UF', 'ANT_MUNIC_', 'ANT_LOCALI', 'ANT_TEMPO_', 'ANT_LOCA_1',
       'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS',
       'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR',
       'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2', 'CLI_OUTR_3',
       'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN', 'ANI_ARANHA',
       'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS', 'NU_AMPOL_1',
       'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7', 'NU_AMPO_5',
       'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND', 'COM_NECROS',
       'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL',
       'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA', 'EVOLUCAO',
       'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

### Reescrita das codificações do dicionário de dados.
Nesta etapa, deve-se reescrever TODAS as codificações do dicionário de dados. Para isso, usamos novamente a função REPLACE

In [21]:
dados['ANT_TEMPO_'] = dados['ANT_TEMPO_'].replace({
    1: '0 - 1h',
    2: '1 - 3h',
    3: '3 - 6h',
    4: '6 - 12h',
    5: '12 e 24h',
    6: '24 e +h',
    9: 'Ignorado'
})

dados['ANT_LOCA_1'] = dados['ANT_LOCA_1'].replace({
    1: 'Cabeça',
    2: 'Braço',
    3: 'Ante-Braço',
    4: 'Mão',
    5: 'Dedo da Mão',
    6: 'tronco',
    7: 'Coxa',
    8: 'Perna',
    9: 'Pé',
    10: 'Dedo do Pé',
    99: 'Ignorado'
})

dados['CLI_TEMPO_'] = dados['CLI_TEMPO_'].replace({
    1 : 'Normal',
    2 : 'Alterado',
    9 : 'Não realizado'
})

dados['TP_ACIDENT'] = dados['TP_ACIDENT'].replace({
    1 : 'Serpente',
    2 : 'Aranha',
    3 : 'Escorpião',
    4 : 'Lagarta',
    5 : 'Abelha',
    6 : 'Outros',
    9 : 'Ignorado'
})

dados['ANI_SERPEN'] = dados['ANI_SERPEN'].replace({
      1: 'Botrópico',
      2: 'Crotálico',
      3: 'Elapídico',
      4: 'Laquético',
      5: 'Serpente não peçonhenta',
      9: 'Ignorado'
      })

dados['ANI_ARANHA'] = dados['ANI_ARANHA'].replace({
      1: 'Foneutrismo',
      2: 'Loxoscelismo',
      3: 'Latrodectismo',
      4: 'Outra aranha',
      9: 'Ignorado'
      })

dados['ANI_LAGART'] = dados['ANI_LAGART'].replace({
      1: 'Lonomia',
      2: 'Outra lagarta',
      9: 'Ignorado',
      })

dados['TRA_CLASSI'] = dados['TRA_CLASSI'].replace({
      1: 'Leve',
      2: 'Moderado',
      3: 'Grave',
      9: 'Ignorado'
      })

dados['EVOLUCAO'] = dados['EVOLUCAO'].replace({
      1: 'Cura',
      2: 'Óbito por acidente por animais peçonhentos',
      3: 'Óbito por outras causas',
      9: 'Ignorado'
      })

dados['CS_GESTANT'] = dados['CS_GESTANT'].replace({
      1: '1º Trimestre',
      2: '2º Trimestre',
      3: '3º Trimestre',
      4: 'Idade gestacional Ignorada',
      5: 'Não',
      6: 'Não se aplica',
      9: 'Ignorado'
      })
dados['CS_RACA'] = dados['CS_RACA'].replace({
      1: 'Branca',
      2: 'Preta',
      3: 'Amarela',
      4: 'Parda',
      5: 'Indígena',
      9: 'Ignorado',
      })
dados['CS_ESCOL_N'] = dados['CS_ESCOL_N'].replace({
      0: 'Analfabeto',
      1: '1ª a 4ª série incompleta do EF (antigo primário ou 1º grau)',
      2: '4ª série completa do EF (antigo primário ou 1º grau)',
      3: '5ª à 8ª série incompleta do EF (antigo ginásio ou 1º grau)',
      4: 'Ensino fundamental completo (antigo ginásio ou 1º grau)',
      5: 'Ensino médio incompleto (antigo colegial ou 2º grau)',
      6: 'Ensino médio completo (antigo colegial ou 2º grau)',
      7: 'Educação superior incompleta',
      8: 'Educação superior completa',
      9: 'Ignorado',
      10: 'Não se aplica'
      })



dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,Preta,Não se aplica,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,Ignorado,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,Indígena,Analfabeto,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,Branca,Ensino médio completo (antigo colegial ou 2º g...,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,Não se aplica,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,Parda,1ª a 4ª série incompleta do EF (antigo primári...,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,Branca,Ignorado,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,Branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18

## TRATAR A COLUNA NU_IDADE_N


A idade no SINAN é utilizada de forma codificada, obedecendo o seguinte critério:
1. Hora
2. Dia
3. Mês
4. Ano

Exemplos:

* 3007 - Sete meses
* 4035 - Trinta e cinco anos

In [23]:
idades = []

for idade in dados['NU_IDADE_N']:
  if idade > 4000:
    idades.append(idade - 4000)
  else:
    idades.append(0)

dados['NU_IDADE_N_'] = idades

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA,NU_IDADE_N_
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,Preta,Não se aplica,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09,4
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,Ignorado,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16,36
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,Indígena,Analfabeto,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25,25
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,Branca,Ensino médio completo (antigo colegial ou 2º g...,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17,62
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,Não se aplica,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,11
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,35
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,Parda,1ª a 4ª série incompleta do EF (antigo primári...,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29,55
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,Branca,Ignorado,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10,45
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,Branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18,19

# Decodificando ID_MUNICIP

A base de dados do SINAN usa o código do IBGE para nome dos municípios

Deve ser usada uma tabela correspondente de código de UF

In [43]:
municipios = pd.read_csv('/content/municipios.csv')

municipios

      COD UF      COD                   NOME
0         11  1100015  Alta Floresta D'oeste
1         11  1100023              Ariquemes
2         11  1100031                 Cabixi
3         11  1100049                 Cacoal
4         11  1100056             Cerejeiras
...      ...      ...                    ...
5565      52  5222005             Vianópolis
5566      52  5222054         Vicentinópolis
5567      52  5222203               Vila Boa
5568      52  5222302          Vila Propício
5569      53  5300108               Brasília

[5570 rows x 3 columns]

Converter em dicionário no qual codigo do municipio : "Nome do Município"

In [44]:
municipios['IBGE'] = (municipios['COD'] // 10).astype('int64')
municipios

      COD UF      COD                   NOME    IBGE
0         11  1100015  Alta Floresta D'oeste  110001
1         11  1100023              Ariquemes  110002
2         11  1100031                 Cabixi  110003
3         11  1100049                 Cacoal  110004
4         11  1100056             Cerejeiras  110005
...      ...      ...                    ...     ...
5565      52  5222005             Vianópolis  522200
5566      52  5222054         Vicentinópolis  522205
5567      52  5222203               Vila Boa  522220
5568      52  5222302          Vila Propício  522230
5569      53  5300108               Brasília  530010

[5570 rows x 4 columns]

In [45]:
municipios = municipios[['IBGE', 'NOME']]
municipios = municipios.set_index('IBGE')

municipios

                         NOME
IBGE
110001  Alta Floresta D'oeste
110002              Ariquemes
110003                 Cabixi
110004                 Cacoal
110005             Cerejeiras
...                       ...
522200             Vianópolis
522205         Vicentinópolis
522220               Vila Boa
522230          Vila Propício
530010               Brasília

[5570 rows x 1 columns]

In [ ]:
#Transformar em dicionário
dicionario_municipios = municipios.to_dict()['NOME']
dicionario_municipios

In [ ]:
dados.info()

In [ ]:
#Usando a função map
dados['ID_MUNICIP_NOME'] = dados['ID_MUNICIP'].map(dicionario_municipios)
dados['ID_MN_RESI_NOME'] = dados['ID_MN_RESI'].map(dicionario_municipios)
dados['ANT_MUNIC_NOME'] = dados['ANT_MUNIC_'].map(dicionario_municipios)

dados

## Ocupação

In [79]:
#Identifiquei que a coluna ID_OCUPA_N é do tipo object, então, preciso transforma-la em inteiro
## Para tal, vou criar uma nova série ID_OCUPA_N_INT
#pd.to_numeric(df['COD'], errors='coerce').astype('Int64')
dados['ID_OCUPA_N_INT'] = pd.to_numeric(dados['ID_OCUPA_N'], errors = 'coerce').astype('Int64')
dados['ID_OCUPA_N_INT'] = dados['ID_OCUPA_N_INT'].astype(str)

In [93]:
ocupacao = pd.read_csv('https://raw.githubusercontent.com/andrejarenkow/csv/refs/heads/master/CBO2002%20-%20Ocupacao.csv')
ocupacao = ocupacao.set_index('CODIGO')
dicionario_ocupacao = ocupacao.to_dict()['TITULO']
dicionario_ocupacao

dados['ID_OCUPA_N_NOME'] = dados['ID_OCUPA_N_INT'].map(dicionario_ocupacao)
dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA,NU_IDADE_N_,ID_MUNICIP_NOME,ID_MN_RESI_NOME,ANT_MUNIC_NOME,ID_OCUPA_N_NOME,ID_OCUPA_N_INT
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,Preta,Não se aplica,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09,4,Feira de Santana,Feira de Santana,Feira de Santana,NaN,<NA>
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,Ignorado,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16,36,Juquitiba,Juquitiba,Juquitiba,NaN,<NA>
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,Indígena,Analfabeto,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25,25,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Produtor agrícola polivalente,612005
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,Branca,Ensino médio completo (antigo colegial ou 2º g...,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17,62,Porto Amazonas,Palmeira,Porto Amazonas,Aposentado/Pensionista,999993
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,Não se aplica,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28,3,Recife,Jurema,Jurema,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,11,São Pedro do Piauí,Angical do Piauí,Angical do Piauí,Estudante,999991
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,35,São Pedro do Piauí,São Pedro do Piauí,São Pedro do Piauí,Dona de casa,999992
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,Parda,1ª a 4ª série incompleta do EF (antigo primári...,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29,55,Coluna,Belo Horizonte,Coluna,Motorista de carro de passeio,782305
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,Branca,Ignorado,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10,45,Araucária,Araucária,Araucária,NaN,<NA>
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,Branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18,19,Vitória da Conquista,Anagé,Anagé,NaN,<NA>

In [96]:
uf = pd.read_csv('https://raw.githubusercontent.com/andrejarenkow/csv/refs/heads/master/cod_uf.csv')
uf = uf.set_index('Código UF')
dicionario_UF = uf.to_dict()['UF']


dados['SG_UF_NOME'] = dados['SG_UF'].map(dicionario_UF)
dados['SG_UF_NOT_NOME'] = dados['SG_UF_NOT'].map(dicionario_UF)
dados['ANT_UF_NOME'] = dados['ANT_UF'].map(dicionario_UF)

dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,ANO_NASC,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,SG_UF,ID_MN_RESI,ID_RG_RESI,ID_PAIS,DT_INVEST,ID_OCUPA_N,ANT_DT_ACI,ANT_UF,ANT_MUNIC_,ANT_LOCALI,ANT_TEMPO_,ANT_LOCA_1,MCLI_LOCAL,CLI_DOR,CLI_EDEMA,CLI_EQUIMO,CLI_NECROS,CLI_LOCAL_,CLI_LOCA_1,MCLI_SIST,CLI_NEURO,CLI_HEMORR,CLI_VAGAIS,CLI_MIOLIT,CLI_RENAL,CLI_OUTR_2,CLI_OUTR_3,CLI_TEMPO_,TP_ACIDENT,ANI_TIPO_1,ANI_SERPEN,ANI_ARANHA,ANI_LAGART,TRA_CLASSI,CON_SOROTE,NU_AMPOLAS,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,COM_LOC,COM_SECUND,COM_NECROS,COM_COMPOR,COM_DEFICT,COM_APUTAC,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA,NU_IDADE_N_,ID_MUNICIP_NOME,ID_MN_RESI_NOME,ANT_MUNIC_NOME,ID_OCUPA_N_NOME,ID_OCUPA_N_INT,SG_UF_NOME,SG_UF_NOT_NOME,ANT_UF_NOME
0,2017-01-01,201701,2017,29,291080,1381.0,2017-01-01,201701,2012.0,4004,M,Não se aplica,Preta,Não se aplica,29.0,291080.0,NaN,1.0,2017-01-01,NaN,2017-01-01,29.0,291080.0,NaN,Ignorado,tronco,Sim,Ignorado,Sim,Ignorado,Ignorado,Ignorado,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaN,NaN,NaN,Ignorado,Cura,NaT,2017-02-02,2017-02-09,4,Feira de Santana,Feira de Santana,Feira de Santana,NaN,<NA>,BA,BA,BA
1,2017-01-01,201701,2017,35,352620,1335.0,2017-01-01,201701,1980.0,4036,F,Ignorado,Ignorado,Ignorado,35.0,352620.0,NaN,1.0,2017-01-01,NaN,2017-01-01,35.0,352620.0,NaN,0 - 1h,Pé,Não,NaN,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Ignorado,NaN,Ignorado,Ignorado,0,0,0,0,0,0,0,0,0,Ignorado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaT,2017-01-02,2017-01-16,36,Juquitiba,Juquitiba,Juquitiba,NaN,<NA>,SP,SP,SP
2,2017-01-01,201701,2017,13,130360,5584.0,2016-05-15,201620,1990.0,4025,F,Não,Indígena,Analfabeto,13.0,130360.0,NaN,1.0,2017-01-01,612005.0,2016-01-15,13.0,130360.0,NaN,12 e 24h,Pé,Sim,Sim,Sim,Sim,Sim,Não,NaN,Sim,Não,Sim,Sim,Não,Não,Não,NaN,Não realizado,Serpente,NaN,Botrópico,NaN,NaN,Grave,Sim,8,0,0,0,0,0,0,0,0,Sim,Sim,Sim,Não,Sim,Sim,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-01,2017-01-25,25,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Santa Isabel do Rio Negro,Produtor agrícola polivalente,612005,AM,AM,AM
3,2017-01-01,201701,2017,41,412010,1357.0,2017-01-01,201701,1954.0,4062,F,Não,Branca,Ensino médio completo (antigo colegial ou 2º g...,41.0,411770.0,NaN,1.0,2017-01-01,999993.0,2017-01-01,41.0,412010.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-02-13,2017-02-17,62,Porto Amazonas,Palmeira,Porto Amazonas,Aposentado/Pensionista,999993,PR,PR,PR
4,2017-01-01,201701,2017,26,261160,1497.0,2017-01-01,201701,2013.0,4003,F,Não se aplica,Ignorado,Não se aplica,26.0,260840.0,NaN,1.0,2017-01-01,NaN,2017-01-01,26.0,260840.0,NaN,0 - 1h,Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-01-02,2017-03-28,3,Recife,Jurema,Jurema,NaN,<NA>,PE,PE,PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222853,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,2006.0,4011,M,Não se aplica,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,220060.0,NaN,1.0,2017-12-31,999991.0,2017-12-31,22.0,220060.0,NaN,0 - 1h,Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,11,São Pedro do Piauí,Angical do Piauí,Angical do Piauí,Estudante,999991,PI,PI,PI
222854,2017-12-31,201801,2017,22,221050,NaN,2017-12-31,201801,1982.0,4035,F,Não,Parda,5ª à 8ª série incompleta do EF (antigo ginásio...,22.0,221050.0,NaN,1.0,2017-12-31,999992.0,2017-12-31,22.0,221050.0,NaN,0 - 1h,Mão,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Escorpião,NaN,NaN,NaN,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2017-12-31,2018-01-17,35,São Pedro do Piauí,São Pedro do Piauí,São Pedro do Piauí,Dona de casa,999992,PI,PI,PI
222855,2017-12-31,201801,2017,31,311680,1450.0,2017-12-31,201801,1962.0,4055,M,Não se aplica,Parda,1ª a 4ª série incompleta do EF (antigo primári...,31.0,310620.0,NaN,1.0,2017-12-31,782305.0,2017-12-31,31.0,311680.0,NaN,1 - 3h,Dedo do Pé,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alterado,Serpente,NaN,Botrópico,NaN,NaN,Leve,Sim,3,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,NaN,NaT,2018-01-29,2018-01-29,55,Coluna,Belo Horizonte,Coluna,Motorista de carro de passeio,782305,MG,MG,MG
222856,2017-12-31,201801,2017,41,410180,1356.0,2017-12-30,201752,1972.0,4045,F,Não,Branca,Ignorado,41.0,410180.0,NaN,1.0,2017-12-31,NaN,2017-12-30,41.0,410180.0,NaN,12 e 24h,Cabeça,Sim,Sim,Sim,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não realizado,Aranha,NaN,NaN,Loxoscelismo,NaN,Leve,Não,0,0,0,0,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,Não,NaN,NaN,NaN,NaN,Não,Cura,NaT,2018-02-10,2018-08-10,45,Araucária,Araucária,Araucária,NaN,<NA>,PR,PR,PR
222857,2017-12-31,201801,2017,29,293330,1398.0,2017-12-31,201801,1998.0,4019,F,Ignorado,Branca,NaN,29.0,290120.0,NaN,1.0,2017-12-31,NaN,2017-12-31,29.0,290120.0,NaN,NaN,Dedo do Pé,Sim,Sim,Não,Não,Não,Não,NaN,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Serpente,NaN,Laquético,NaN,NaN,Moderado,Sim,0,0,0,8,0,0,0,0,0,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ignorado,NaN,NaT,NaT,2019-10-18,19,Vitória da Conquista,Anagé,Anagé,NaN,<NA>,BA,BA,BA

In [94]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222858 entries, 0 to 222857
Data columns (total 80 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   DT_NOTIFIC       222858 non-null  datetime64[ns]
 1   SEM_NOT          222858 non-null  int64
 2   NU_ANO           222858 non-null  int64
 3   SG_UF_NOT        222858 non-null  int64
 4   ID_MUNICIP       222858 non-null  int64
 5   ID_REGIONA       212929 non-null  float64
 6   DT_SIN_PRI       222858 non-null  datetime64[ns]
 7   SEM_PRI          222858 non-null  int64
 8   ANO_NASC         219324 non-null  object
 9   NU_IDADE_N       222858 non-null  int64
 10  CS_SEXO          222858 non-null  object
 11  CS_GESTANT       222851 non-null  object
 12  CS_RACA          219292 non-null  object
 13  CS_ESCOL_N       199978 non-null  object
 14  SG_UF            222784 non-null  float64
 15  ID_MN_RESI       222784 non-null  float64
 16  ID_RG_RESI       0 non-null       float64
 17  ID_PAIS          222857 non-null  float64
 18  DT_INVEST        222858 non-null  datetime64[ns]
 19  ID_OCUPA_N       113134 non-null  object
 20  ANT_DT_ACI       222849 non-null  datetime64[ns]
 21  ANT_UF           222849 non-null  float64
 22  ANT_MUNIC_       222849 non-null  float64
 23  ANT_LOCALI       0 non-null       float64
 24  ANT_TEMPO_       216993 non-null  object
 25  ANT_LOCA_1       222849 non-null  object
 26  MCLI_LOCAL       221008 non-null  object
 27  CLI_DOR          207069 non-null  object
 28  CLI_EDEMA        207061 non-null  object
 29  CLI_EQUIMO       207041 non-null  object
 30  CLI_NECROS       207040 non-null  object
 31  CLI_LOCAL_       207027 non-null  object
 32  CLI_LOCA_1       26503 non-null   object
 33  MCLI_SIST        218133 non-null  object
 34  CLI_NEURO        15495 non-null   object
 35  CLI_HEMORR       15495 non-null   object
 36  CLI_VAGAIS       15495 non-null   object
 37  CLI_MIOLIT       15494 non-null   object
 38  CLI_RENAL        15494 non-null   object
 39  CLI_OUTR_2       15493 non-null   object
 40  CLI_OUTR_3       6844 non-null    object
 41  CLI_TEMPO_       195157 non-null  object
 42  TP_ACIDENT       222849 non-null  object
 43  ANI_TIPO_1       9279 non-null    object
 44  ANI_SERPEN       28738 non-null   object
 45  ANI_ARANHA       33112 non-null   object
 46  ANI_LAGART       5164 non-null    object
 47  TRA_CLASSI       218123 non-null  object
 48  CON_SOROTE       222849 non-null  object
 49  NU_AMPOLAS       222858 non-null  int64
 50  NU_AMPOL_1       222858 non-null  int64
 51  NU_AMPOL_8       222858 non-null  int64
 52  NU_AMPOL_6       222858 non-null  int64
 53  NU_AMPOL_4       222858 non-null  int64
 54  NU_AMPO_7        222858 non-null  int64
 55  NU_AMPO_5        222858 non-null  int64
 56  NU_AMPOL_9       222858 non-null  int64
 57  NU_AMPOL_3       222858 non-null  int64
 58  COM_LOC          209695 non-null  object
 59  COM_SECUND       2669 non-null    object
 60  COM_NECROS       2666 non-null    object
 61  COM_COMPOR       2666 non-null    object
 62  COM_DEFICT       2665 non-null    object
 63  COM_APUTAC       2665 non-null    object
 64  COM_SISTEM       207942 non-null  object
 65  COM_RENAL        853 non-null     object
 66  COM_EDEMA        852 non-null     object
 67  COM_SEPTIC       852 non-null     object
 68  COM_CHOQUE       852 non-null     object
 69  DOENCA_TRA       212492 non-null  object
 70  EVOLUCAO         211354 non-null  object
 71  DT_OBITO         216 non-null     datetime64[ns]
 72  DT_ENCERRA       217816 non-null  datetime64[ns]
 73  DT_DIGITA        222858 non-null  datetime64[ns]
 74  NU_IDADE_N_      222858 non-null  int64
 75  ID_MUNICIP_NOME  222858 non-null  object
 76  ID_MN_RESI_NOME  222741 non-null  object
 77  ANT_MUNIC_NOME   221680 non-null  object
 78  ID_OCUPA_N_NOME  112343 non-null  object
 79  ID_OCUPA_N_INT   222858 non-null  object
dtypes: datetime64[ns](7), float64(8), int64(16), object(49)
memory usage: 136.0+ MB